package recorder

import (
	"fmt"
	"go/format"
	"hash/fnv"
	"path/filepath"
	"strings"
	"time"
	"unicode/utf8"

	tea "charm.land/bubbletea/v2"
	"github.com/mattn/go-runewidth"
)

// burstGap splits typing into separate Type(...) calls when the user pauses.
const burstGap = 2 * time.Second

// waitGap is the idle time after which the user was presumably waiting for
// something (an agent answer, a dialog); combined with new frame content it
// triggers a synthesized WaitFor.
const waitGap = time.Second

// maxAnchorRunes caps the length of synthesized WaitFor anchors.
const maxAnchorRunes = 60

// GenerateOptions parameterizes the generated test source.
type GenerateOptions struct {
	// TestName is the Go test function name. Derive it with TestNameFromPath
	// so it stays a valid identifier.
	TestName string
	// AgentFile is the agent YAML the session ran with, referenced (and to be
	// copied) into the test's testdata directory.
	AgentFile string
	// CassettePath is the model-traffic cassette recorded alongside the input.
	CassettePath string
}

// TestNameFromPath derives a Go test name from a cassette path, e.g.
// "cagent-recording-17.yaml" becomes "TestRecordedCagentRecording17". Paths
// with no usable characters fall back to a deterministic hash so distinct
// recordings never collapse to the same test name.
func TestNameFromPath(path string) string {
	base := strings.TrimSuffix(filepath.Base(path), ".yaml")
	var b strings.Builder
	upperNext := true
	for _, r := range base {
		switch {
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z', r >= '0' && r <= '9':
			if upperNext && r >= 'a' && r <= 'z' {
				r -= 'a' - 'A'
			}
			b.WriteRune(r)
			upperNext = false
		default:
			upperNext = true
		}
	}
	if b.Len() == 0 {
		h := fnv.New32a()
		h.Write([]byte(base))
		fmt.Fprintf(&b, "%08X", h.Sum32())
	}
	return "TestRecorded" + b.String()
}

// GenerateTest renders the recorded session as a tuitest e2e test. It is not
// goroutine-safe with the Bubble Tea message loop: call it only after
// Program.Run has returned, never while the program is still running.
func (r *Recorder) GenerateTest(opts GenerateOptions) string {
	events, quitFrame, quitTrimmed := trimTrailingQuit(r.events)

	// The frame to synthesize the final WaitFor from: what the user saw when
	// they quit, or the model's final render when no quit keys were recorded.
	finalFrame := r.frame()
	if quitTrimmed {
		finalFrame = quitFrame
	}

	chain, needsTea := buildChain(events, finalFrame)

	width, height := r.width, r.height
	if width == 0 || height == 0 {
		width, height = 120, 40
	}

	testName := opts.TestName
	if testName == "" {
		testName = TestNameFromPath(opts.CassettePath)
	}

	agentPath := "testdata/" + agentBaseName(opts.AgentFile)
	agentSource := opts.AgentFile
	if agentSource == "" {
		agentSource = "<the agent configuration this session ran with>"
	}

	var b strings.Builder
	fmt.Fprintf(&b, `// Code generated by 'docker-agent run --record'. Edit before committing.
//
// To turn this into a runnable e2e test:
//  1. mv %[1]s e2e/tui/testdata/cassettes/%[2]s.yaml
//     (the cassette file name must match the test name)
//  2. cp %[3]s e2e/tui/testdata/ (the test loads it as %[4]s).
//     For a built-in, alias, or registry agent, materialize its YAML there
//     instead — the replay needs the exact configuration this session used.
//  3. mv this file e2e/tui/
//  4. Review the synthesized WaitFor anchors: replace any time- or
//     machine-dependent text with stable content, and trim leftover
//     quit keystrokes at the end of the chain.
package tui_test

import (
	"testing"
`, commentSafe(opts.CassettePath), testName, commentSafe(agentSource), agentPath)
	if needsTea {
		b.WriteString("\n\ttea \"charm.land/bubbletea/v2\"\n")
	}
	b.WriteString("\n\t\"github.com/docker/docker-agent/pkg/tui/tuitest\"\n)\n\n")

	fmt.Fprintf(&b, "func %s(t *testing.T) {\n", testName)
	fmt.Fprintf(&b, "\td := newTUI(t, %q, %d, %d)\n\n", agentPath, width, height)
	fmt.Fprintf(&b, "\td.%s\n}\n", strings.Join(chain, ".\n\t\t"))

	src := b.String()
	if formatted, err := format.Source([]byte(src)); err == nil {
		return string(formatted)
	}
	return src
}

// agentBaseName maps the agent reference the session ran with to a YAML file
// name for the generated test's testdata directory. Non-file references
// (default agent, built-ins, aliases, registry refs) fall back to a name the
// user must materialize, per the generated header instructions.
func agentBaseName(agentFile string) string {
	base := filepath.Base(agentFile)
	if base == "." || base == "/" || base == "" {
		return "agent.yaml"
	}
	if !strings.HasSuffix(base, ".yaml") && !strings.HasSuffix(base, ".yml") {
		return base + ".yaml"
	}
	return base
}

// commentSafe strips control characters from s so user-supplied paths cannot
// break out of the generated file's header comment.
func commentSafe(s string) string {
	return strings.Map(func(r rune) rune {
		if r < ' ' || r == 0x7f {
			return ' '
		}
		return r
	}, s)
}

// buildChain converts recorded events into tuitest DSL calls, interleaving
// synthesized WaitFor calls where the user visibly waited for new content.
func buildChain(events []event, finalFrame string) (chain []string, needsTea bool) {
	// The initial wait mirrors the hand-written e2e tests: interact only once
	// the first screen has rendered.
	chain = append(chain, `WaitFor(tuitest.Not(tuitest.Contains("Loading")))`)

	var prev *event
	for i := 0; i < len(events); {
		e := events[i]

		// The user pausing before this input usually means they were waiting
		// for the agent; anchor the replay on content that appeared meanwhile.
		if prev != nil && e.at.Sub(prev.at) >= waitGap {
			if anchor := diffAnchor(prev.frame, e.frame); anchor != "" {
				chain = append(chain, fmt.Sprintf("WaitFor(tuitest.Contains(%q))", anchor))
			}
		}

		switch {
		case e.kind == clickEvent:
			chain = append(chain, clickCall(e))
			prev = &events[i]
			i++
		case isTyping(e.key):
			var text strings.Builder
			j := i
			for j < len(events) && events[j].kind == keyEvent && isTyping(events[j].key) &&
				(j == i || events[j].at.Sub(events[j-1].at) < burstGap) {
				text.WriteString(events[j].key.Text)
				j++
			}
			chain = append(chain, fmt.Sprintf("Type(%q)", text.String()))
			prev = &events[j-1]
			i = j
		default:
			call, usesTea := keyCall(e.key)
			needsTea = needsTea || usesTea
			chain = append(chain, call)
			prev = &events[i]
			i++
		}
	}

	// Wait for whatever the last input produced (typically the agent's final
	// answer) so the test observes the finished state before exiting.
	if prev != nil {
		if anchor := diffAnchor(prev.frame, finalFrame); anchor != "" {
			chain = append(chain, fmt.Sprintf("WaitFor(tuitest.Contains(%q))", anchor))
		}
	}
	return chain, needsTea
}

// trimTrailingQuit drops the trailing Ctrl+C/Ctrl+D presses that ended the
// session; replayed tests are torn down by the harness instead. It returns
// the frame of the first dropped event — the settled screen the user quit
// from — for the final WaitFor.
func trimTrailingQuit(events []event) (kept []event, quitFrame string, trimmed bool) {
	end := len(events)
	for end > 0 {
		e := events[end-1]
		if e.kind != keyEvent || !isQuitKey(e.key) {
			break
		}
		quitFrame = e.frame
		trimmed = true
		end--
	}
	return events[:end], quitFrame, trimmed
}

// isQuitKey reports whether k is Ctrl+C or Ctrl+D. Bubble Tea v2 represents
// both as {Mod: ModCtrl, Code: letter} on the legacy and Kitty input paths
// alike; lock states (Caps/Num/Scroll) ride along in Mod under Kitty and are
// masked out, and BaseCode covers non-latin keyboard layouts.
func isQuitKey(k tea.KeyPressMsg) bool {
	const lockModifiers = tea.ModCapsLock | tea.ModNumLock | tea.ModScrollLock
	if k.Mod&^lockModifiers != tea.ModCtrl {
		return false
	}
	code := k.Code
	if k.BaseCode != 0 {
		code = k.BaseCode
	}
	return code == 'c' || code == 'd'
}

// isTyping reports whether k is a plain printable key press that belongs in a
// Type(...) burst.
func isTyping(k tea.KeyPressMsg) bool {
	if k.Mod != 0 || k.Text == "" {
		return false
	}
	for _, r := range k.Text {
		if r < ' ' || r == 0x7f {
			return false
		}
	}
	return true
}

// keyNames maps special key codes to their tea constant names for Press calls.
var keyNames = map[rune]string{
	tea.KeyEnter:     "tea.KeyEnter",
	tea.KeyEscape:    "tea.KeyEscape",
	tea.KeyTab:       "tea.KeyTab",
	tea.KeyBackspace: "tea.KeyBackspace",
	tea.KeyDelete:    "tea.KeyDelete",
	tea.KeyInsert:    "tea.KeyInsert",
	tea.KeyUp:        "tea.KeyUp",
	tea.KeyDown:      "tea.KeyDown",
	tea.KeyLeft:      "tea.KeyLeft",
	tea.KeyRight:     "tea.KeyRight",
	tea.KeyHome:      "tea.KeyHome",
	tea.KeyEnd:       "tea.KeyEnd",
	tea.KeyPgUp:      "tea.KeyPgUp",
	tea.KeyPgDown:    "tea.KeyPgDown",
	tea.KeyF1:        "tea.KeyF1",
	tea.KeyF2:        "tea.KeyF2",
	tea.KeyF3:        "tea.KeyF3",
	tea.KeyF4:        "tea.KeyF4",
	tea.KeyF5:        "tea.KeyF5",
	tea.KeyF6:        "tea.KeyF6",
	tea.KeyF7:        "tea.KeyF7",
	tea.KeyF8:        "tea.KeyF8",
	tea.KeyF9:        "tea.KeyF9",
	tea.KeyF10:       "tea.KeyF10",
	tea.KeyF11:       "tea.KeyF11",
	tea.KeyF12:       "tea.KeyF12",
}

// keyCall renders a non-typing key press as a Press/Enter DSL call and
// reports whether the generated code references the tea package.
func keyCall(k tea.KeyPressMsg) (call string, needsTea bool) {
	if k.Code == tea.KeyEnter && k.Mod == 0 {
		return "Enter()", false
	}

	var mods []string
	for _, m := range []struct {
		bit  tea.KeyMod
		name string
	}{
		{tea.ModShift, "tea.ModShift"},
		{tea.ModAlt, "tea.ModAlt"},
		{tea.ModCtrl, "tea.ModCtrl"},
		{tea.ModMeta, "tea.ModMeta"},
		{tea.ModSuper, "tea.ModSuper"},
		{tea.ModHyper, "tea.ModHyper"},
	} {
		if k.Mod&m.bit != 0 {
			mods = append(mods, m.name)
		}
	}
	modArgs := ""
	if len(mods) > 0 {
		modArgs = ", " + strings.Join(mods, ", ")
	}

	if name, ok := keyNames[k.Code]; ok {
		return fmt.Sprintf("Press(%s%s)", name, modArgs), true
	}
	return fmt.Sprintf("Press(%q%s)", k.Code, modArgs), len(mods) > 0
}

// clickCall renders a mouse click. When the text under the cursor is unique
// in the frame it clicks by text (resilient to layout shifts); otherwise it
// falls back to raw coordinates.
func clickCall(e event) string {
	if word := wordAt(e.frame, e.x, e.y); word != "" && strings.Count(e.frame, word) == 1 {
		return fmt.Sprintf("ClickText(%q)", word)
	}
	return fmt.Sprintf("Click(%d, %d)", e.x, e.y)
}

// wordAt returns the space-delimited word covering display column x on line y
// of frame, or "" if the position is blank or out of bounds. x is a display
// width, so wide Unicode before the click is handled.
func wordAt(frame string, x, y int) string {
	lines := strings.Split(frame, "\n")
	if y < 0 || y >= len(lines) {
		return ""
	}
	runes := []rune(lines[y])

	idx := -1
	col := 0
	for i, r := range runes {
		w := runewidth.RuneWidth(r)
		if x < col+w {
			idx = i
			break
		}
		col += w
	}
	if idx < 0 || runes[idx] == ' ' {
		return ""
	}

	lo, hi := idx, idx
	for lo > 0 && runes[lo-1] != ' ' {
		lo--
	}
	for hi < len(runes)-1 && runes[hi+1] != ' ' {
		hi++
	}
	return string(runes[lo : hi+1])
}

// borderCutset is trimmed off frame lines before they are considered as
// WaitFor anchors, so box-drawing chrome never anchors a wait.
const borderCutset = " \t│┃║╭╮╰╯└┘┌┐├┤┬┴─━┄┅┆┇┈┉"

// diffAnchor picks the most useful line that is present in next but not in
// prev — the longest new line, which biases toward real message content over
// status-bar churn. The result is capped so goldens stay readable.
func diffAnchor(prev, next string) string {
	prevLines := make(map[string]bool)
	for line := range strings.SplitSeq(prev, "\n") {
		prevLines[strings.Trim(line, borderCutset)] = true
	}

	best := ""
	for line := range strings.SplitSeq(next, "\n") {
		s := strings.Trim(line, borderCutset)
		if utf8.RuneCountInString(s) < 4 || prevLines[s] || hasSpinner(s) {
			continue
		}
		if utf8.RuneCountInString(s) > utf8.RuneCountInString(best) {
			best = s
		}
	}
	return truncateRunes(best, maxAnchorRunes)
}

// hasSpinner reports whether s contains braille spinner glyphs, which animate
// between frames and would make an anchor flaky.
func hasSpinner(s string) bool {
	for _, r := range s {
		if r >= 0x2800 && r <= 0x28FF {
			return true
		}
	}
	return false
}

func truncateRunes(s string, n int) string {
	runes := []rune(s)
	if len(runes) <= n {
		return s
	}
	return strings.TrimRight(string(runes[:n]), " ")
}
